### ISSUE TITLE
Grub Önyükleyici Yavaş Çalışıyor

### ISSUE THREAD

**Issue by kurth4cker** [mahmutelmas06/PardusYAMA#2]
Ben bu uygulama ile sadece grub teması ile ilgili seçeneği seçip temayı kurduğumda grub önyükleyici ayarları kötü bir hal aldı.
Pardus kurulurken grub kurulmamıştı ben de 
`apt install grub2`
diyerek kurdum. Yarı pardus önyükeyicisine benzeyen bir görünümü oldu böyle olunca. Ama bu temayı kurunca grubda:

- Yazılar daha büyük gözükmeye başladı.
- Aşağı-yukarı seçenek değiştirme tuşuna her bastığımda ancak birkaç saniye sonra tepki veriyor. 
- **System Setup** menüsü kaldırılmış.

Hata sizin uygulamanızdan mı kaynaklanıyor bilmiyorum. Temayı kaldırmalı mıyım? Nasıl bir ayar yapmalıyım?

**Not:** Daha önce (Pardus grubu başarılı bir şekilde kurduğunda) bu grub teması kusursuz çalışıyordu.

**Comment by mahmutelmas06** [comment]
Muhtemelen Grub sonradan yuklenince pardustaki bazi ayarlar yuklu gelmiyor. Buda temalarda sorun cikariyor.

Kok dizinde etc/default/grub dizininde "grub" isimli bir dosya var. Onu dogrudan buraya yada metin duzenleyici ile acip icindekileri buraya yapistirabilirseniz eksikligi bulup sorunu cozebiliriz.

**Comment by kurth4cker** [comment]
[grub.txt](https://github.com/mahmutelmas06/PardusYAMA/files/5359283/grub.txt)

![resim](https://user-images.githubusercontent.com/61054662/95659235-4938f900-0b28-11eb-9bcd-ab65d41c74f6.png)

**Comment by kurth4cker** [comment]
![20201010_204545](https://user-images.githubusercontent.com/61054662/95661748-61b20f00-0b3a-11eb-8604-20e13254d47e.jpg)

Grub customizer ile birşeyler yaptım. Tema yok şu an ama **System Setup** menüsünü nasıl getireceğimi bilmiyorum.

**Comment by mahmutelmas06** [comment]
System Setup menüsünden kastınızı anlamadım. Varsayılan Grub bu resimdekinden fazla seçenek sunmuyor.

**Comment by Yusuf-Kozan** [comment]
Benim bilgisayarlardaki GRUB menüsünde öntanımlı gelen seçenekler arasında da BIOS veya UEFI menüsüne yönlendiren `System Setup` seçeneği var. Şimdi Grub Customizer'dan baktım betiğe, içinde sadece şu yazılıydı:
```
fwsetup
```
